import turtle
window = turtle.Screen()
leonardo = turtle.Turtle()

for i in range(4) :
    leonardo.forward(50)
    leonardo.right(90)

for i in range(7) :
    leonardo.forward(50)
    leonardo.right(60)

for i in range(9) :
    leonardo.forward(50)
    leonardo.right(45)

for i in range(19) :
    leonardo.forward(50)
    leonardo.right(20)

tess = turtle.Turtle()
tess.color("Red")

for i in range(5) :
    tess.forward(100)
    tess.right(144)

t = turtle.Turtle()

t.color("Green")
t.shape('turtle')

t.penup()
t.left(90)
t.forward(110)
t.right(90)
t.pendown()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.right(135)
t.forward(71)
t.right(90)
t.forward(71)
t.right(90)
t.forward(140)
t.right(135)
t.forward(100)
t.right(135)
t.forward(140)

leonardo = turtle.Turtle()
leonardo.color("red")
leonardo.speed(5)
leonardo.penup()
leonardo.forward(100)
leonardo.pendown()
leonardo.forward(50)
leonardo.dot(5)
leonardo.stamp()
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(100)
leonardo.color("blue")
leonardo.right(90)
leonardo.forward(100)
leonardo.pencolor("green")
leonardo.right(90)
leonardo.forward(100)
leonardo.right(45)
leonardo.forward(70)
leonardo.right(90)
leonardo.forward(70)
leonardo.right(45)
leonardo.forward(50)
leonardo.left(90)
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(50)
leonardo.right(45)
leonardo.forward(50)
leonardo.right(45)
leonardo.forward(50)
leonardo.right(135)
leonardo.forward(50)
leonardo.right(180)
leonardo.forward(50)
leonardo.right(135)
leonardo.forward(50)
leonardo.right(45)
leonardo.forward(50)
leonardo.right(45)
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(100)
leonardo.right(45)
leonardo.forward(50)
leonardo.right(135)
leonardo.forward(50)
leonardo.right(180)
leonardo.forward(50)
leonardo.left(45)
leonardo.forward(70)
leonardo.left(90)
leonardo.forward(50)
leonardo.left(45)
leonardo.penup()
leonardo.forward(150)
leonardo.pendown()
leonardo.showturtle()
leonardo.left(180)
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(25)
leonardo.right(90)
leonardo.forward(50)
leonardo.right(90)
leonardo.penup()
leonardo.forward(50)
leonardo.right(90)
leonardo.forward(50)
leonardo.pendown()
leonardo.forward(5)
leonardo.left(90)
leonardo.forward(60)
leonardo.left(90)
leonardo.forward(20)
leonardo.left(90)
leonardo.forward(60)
leonardo.left(3645)

window.mainloop()
